### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by WarlyFarly-Github** [LilDrippyMyFnf/V.S.Stupid2.5FnfMod#1]
the xml and png are broken
when i load the character editor it shows the whole spritesheet

**Comment by LilDrippyMyFnf** [comment]
> the xml and png are broken when i load the character editor it shows the whole spritesheet

idk how to fix it

just make your version of it

**Comment by LilDrippyMyFnf** [comment]
> > the xml and png are broken when i load the character editor it shows the whole spritesheet
> 
> idk how to fix it
> 
> just make your version of it

or just try to fix it








its outdated anyway

**Comment by WarlyFarly-Github** [comment]
> > > the xml and png are broken when i load the character editor it shows the whole spritesheet
> > 
> > 
> > idk how to fix it
> > just make your version of it
> 
> or just try to fix it
> 
> its outdated anyway

ok

**Comment by LilDrippyMyFnf** [comment]
> > > > the xml and png are broken when i load the character editor it shows the whole spritesheet
> > > 
> > > 
> > > idk how to fix it
> > > just make your version of it
> > 
> > 
> > or just try to fix it
> > its outdated anyway
> 
> ok i'll make him over DD

daddy dearest
